var galleries = {
            pdp11: [
                            {src:"/images/pdp11/racks.jpg", w:2448, h:3264, title:"H960 racks: the backbones"},
                            {src:"/images/pdp11/kb11a-backplane.jpg", w:2448, h:2448, title:"KB11-A CPU backplane"},
                            {src:"/images/pdp11/rk11c.jpg", w:2448, h:2448, title:"RK11-C disk controller backplane"},
                            {src:"/images/pdp11/rk05-help.png", w:1340, h:339, title:"Help getting the RK05 drives off the floor -- thanks, Chris!"},
                            {src:"/images/pdp11/861.jpg", w:2448, h:3264, title:"H861 AC power controller"},
                            {src:"/images/pdp11/h742-teardown.jpg", w:2448, h:2448, title:"Tearing down the H742 power supplies"},
                            {src:"/images/pdp11/h742-corrosion.jpg", w:2448, h:2448, title:"Corrosion on part of an H742 chassis, to be sanded and painted"},
                            {src:"/images/pdp11/cpu-cabinet.jpg", w:2448, h:2448, title:"CPU cabinet getting some touch-up paint after sanding corroded spots"},
                            {src:"/images/pdp11/pwr-ctrls.jpg", w:3264, h:2448, title:"H742 power controller boards"},
                            {src:"/images/pdp11/chassis-with-fans.jpg", w:2448, h:3264, title:"CPU cabinet with restored cooling fans"},
                            {src:"/images/pdp11/742-rebuild.jpg", w:3264, h:2448, title:"Deeper into the H742s for cleaning, sanding, and painting"},
                            {src:"/images/pdp11/742s-mounted.jpg", w:2448, h:2448, title:"H742s and CPU cabinet remounted"},
                            {src:"/images/pdp11/front-panel.jpg", w:2448, h:3264, title:"Front panel remounted -- starting to look like a real PDP-11!"},
                            {src:"/images/pdp11/boards-in-chassis.jpg", w:2448, h:2448, title:"CPU and MMU logic installed.  Empty slots on the right are for the FPU."},
                            {src:"/images/pdp11/board-with-crystals.jpg", w:2448, h:2448, title:"Logic board with crystals after several decades of storage"},
                            {src:"/images/pdp11/crystals.jpg", w:2448, h:2448, title:"Closeup of crystals on logic board"},
                            {src:"/images/pdp11/knuckles.jpg", w:2448, h:2448, title:"The characteristic bloody knuckles that are obtained whenever wrestling with PDP backplanes, logic cards, and terminators in close confines"},
                            {src:"/images/pdp11/vt52.jpg", w:2448, h:2448, title:"VT52 hooked up to a Linux VM for a test drive"},
                            {src:"/images/pdp11/rom-scanner.jpg", w:2448, h:2448, title:"Homemade FPGA ROM scanner used to read out the VT52 character generator ROM"},
                            {src:"/images/pdp11/boards-in-chassis-2.jpg", w:3264, h:2448, title:"Backplane and expansion populated with CPU, MMU, FPU, bootstrap ROM, console serial, 256K RAM, grant continuity cards and terminators"},
                            {src:"/images/pdp11/mr11-with-note.jpg", w:3264, h:2448, title:"A modified M792-YB bootstrap ROM, with a vintage note attached"},
                            {src:"/images/pdp11/mr11-bare.jpg", w:3264, h:2448, title:"M792-YB bootstrap ROM with note removed"},
                            {src:"/images/pdp11/harness-parts.jpg", w:3264, h:2448, title:"Wire, connectors, and crimp tool to get started on replacement power harness"},
                            {src:"/images/pdp11/harness-bench.jpg", w:3264, h:2448, title:"Partially completed replacement power harness"},
                            {src:"/images/pdp11/harness-progress.jpg", w:3264, h:2448, title:"Finishing up the replacement power harness in the rack"},
                            {src:"/images/pdp11/harness-complete.jpg", w:3264, h:2448, title:"Completed power harness from above rear"},
                            {src:"/images/pdp11/power-supplies.jpg", w:3264, h:2448, title:"Completed power harness from side"},
                            {src:"/images/pdp11/initial-power-on.jpg", w:3024, h:3024, title:"Initial power on!  No smoke, but all lights on (not right).  Well, it&#39;s a start!"},
                            {src:"/images/pdp11/power-lights.jpg", w:3024, h:3024, title:"Power supply with all regulator lamps repaired"},
                            {src:"/images/pdp11/km11.jpg", w:4032, h:3024, title:"Tom Uban KM11 replica, stuffed with parts and ready to go"},
                            {src:"/images/pdp11/km11-action.jpg", w:3024, h:4032, title:"Tom Uban KM11 replica in action"},
                            {src:"/images/pdp11/ms11-debug.jpg", w:4032, h:3024, title:"MS11 memory card debug in progress, with board extender, logic analyzer, and KM11"},
                            {src:"/images/pdp11/ms11-repaired.jpg", w:3024, h:3024, title:"MS11 with two bad 4116 RAMs pulled, socketed, and replaced"},
                            {src:"/images/pdp11/m9301-running.jpg", w:4032, h:3024, title:"VT52 attached, and running now in the M9301 bootstrap monitor!"},
                            {src:"/images/pdp11/pdp11gui.jpg", w:4032, h:3024, title:"PDP11GUI hooked up and running; ready to start downloading and running diagnostics"},
                            {src:"/images/pdp11/vt52-repair.jpg", w:3024, h:3024, title:"VT52 open for repairs with new clock oscillator installed"},
                            {src:"/images/pdp11/prom-programmer.jpg", w:3024, h:3024, title:"Data I/O series 22 PROM programmer, arrived from eBay"},
                            {src:"/images/pdp11/alu-prom-replaced.jpg", w:3024, h:3024, title:"GRA board with replaced ALU PROM"},
                            {src:"/images/pdp11/h720e-breakdown.jpg", w:4032, h:3024, title:"Tearing down the H720E power supply for the RK11 storage controller"},
                            {src:"/images/pdp11/h720e-leaking-cap.jpg", w:3024, h:3024, title:"Leaking tantalum cap on H720e regulator board"},
                            {src:"/images/pdp11/cabinets.jpg", w:3024, h:4032, title:"Cabinet side panels and decorative top panels cleaned and installed"},
                            {src:"/images/pdp11/basic.jpg", w:3024, h:3024, title:"Running papertape BASIC, loaded via PDP11GUI"},
                            {src:"/images/pdp11/720e-caps.jpg", w:3024, h:3024, title:"H720e regulator card with refreshed caps"},
                            {src:"/images/pdp11/rk11-racked.jpg", w:3024, h:4032, title:"RK11-C controller installed in rack, with temporary jumper hack for flown cap"},
                            {src:"/images/pdp11/bc11-good.jpg", w:3024, h:3024, title:"A BC11-A bus cable, with vintage label"},
                            {src:"/images/pdp11/rk11-back.jpg", w:3024, h:3024, title:"RK11-C controller from the back, flipchips and cabling visible"},
                            {src:"/images/pdp11/m203.jpg", w:3024, h:3024, title:"A failing M203, the cause of a stuck bit in RK11 register RKDB"},
                            {src:"/images/pdp11/rk05.jpg", w:4032, h:3024, title:"RK05 drive internals"},
                            {src:"/images/pdp11/h743.jpg", w:3024, h:3024, title:"H743 power supply pulled and on bench"},
                            {src:"/images/pdp11/rk05-lower-before.jpg", w:3024, h:3024, title:"First RK05 lower head before cleaning"},
                            {src:"/images/pdp11/rk05-lower-after.jpg", w:3024, h:3024, title:"First RK05 lower head after cleaning"},
                            {src:"/images/pdp11/rk05-upper-before.jpg", w:3024, h:3024, title:"First RK05 upper head before cleaning"},
                            {src:"/images/pdp11/rk05-upper-after.jpg", w:3024, h:3024, title:"First RK05 upder head after cleaning"},
                            {src:"/images/pdp11/lower-cover-abrasions.jpg", w:3024, h:3024, title:"Abrasions on first RK05 lower cover, from contact with spindle motor shafts"},
                            {src:"/images/pdp11/rk05-cartridge-foam.jpg", w:400, h:400, title:"Foam inside the hub of an RK05 pack -- could be bad news if this is decaying like other DEC foam..."},
                            {src:"/images/pdp11/rk05-running.jpg", w:3024, h:3024, title:"RK05 running offline from controller; pack spinning and heads loaded"},
                            {src:"/images/pdp11/BC11-woes.jpg", w:3024, h:3024, title:"A box of BC11-A cables to be sorted through..."},
                            {src:"/images/pdp11/rkdp-boot.jpg", w:3024, h:3024, title:"First boot off disk -- RKDP diagnostics pack!"},
                            {src:"/images/pdp11/G740.jpg", w:3024, h:3024, title:"G740 Disk Selection flipchip, jumpered for two drives"},
                            {src:"/images/pdp11/M9301.jpg", w:3024, h:3024, title:"M9301-YB bootstrap ROM"},
                            {src:"/images/pdp11/M792-YB.jpg", w:3024, h:3024, title:"M792-YB diode-matrix bootstrap ROM"},
                            {src:"/images/pdp11/rt11-boots.jpg", w:4032, h:3024, title:"At long last: RT-11 boots from an RK05 pack!"},
                            {src:"/images/pdp11/rk05-packs.jpg", w:3024, h:3024, title:"Some of the RK05 packs obtained in a surplus auction downstream of Stanford&#39;s Hansen Experimental Physics Lab"},
                            {src:"/images/pdp11/head-crashes.jpg", w:3024, h:4032, title:"An RK05 disk platter with obvious head crashes"},
                            {src:"/images/pdp11/gravity-pack.jpg", w:4032, h:3024, title:"RK05 pack spinning in drive with heads loaded"},
                            {src:"/images/pdp11/vt52-guts.jpg", w:4032, h:3024, title:"VT52 with logic boards and keyboard removed"},
                            {src:"/images/pdp11/vt52-keys.jpg", w:4032, h:3024, title:"VT52 keyboard under test, powered from bench supply"},
                            {src:"/images/pdp11/rt11-adventure.jpg", w:3024, h:3024, title:"VT52 test drive with RT-11 Adventure"},
                            {src:"/images/pdp11/la30-cap.jpg", w:3024, h:3024, title:"PCB-containing cap from ferro-resonant supply; to be replaced"},
                            {src:"/images/pdp11/la30-supply.jpg", w:4032, h:3024, title:"LA30 H735 supply, pulled to bench for clean/refurb"},
                            {src:"/images/pdp11/la30-cards.jpg", w:3024, h:3024, title:"LA30 internal controller card cage"},
                            {src:"/images/pdp11/la30-head.jpg", w:3024, h:3024, title:"LA30 print head"},
                            {src:"/images/pdp11/la30-carriage.jpg", w:4032, h:3024, title:"LA30 carriage, disassembled for clean, repairs, and lube.  A mangled paper drag spring is visible on the print bar assembly."},
                            {src:"/images/pdp11/la30-cleaned.jpg", w:4032, h:3024, title:"LA30 cleaned and reassembled"},
                            {src:"/images/pdp11/kr2736.jpg", w:4032, h:3024, title:"The SMC KR2736-17 keyboard scanner/encoder in the LA30"},
                            {src:"/images/pdp11/G380.jpg", w:4032, h:3024, title:"G380 solenoid driver card from the LA30, with failed parts pulled"},
                            {src:"/images/pdp11/VCFW3.jpg", w:720, h:960, title:"Reassembly on the VCF West show floor"},
                            {src:"/images/pdp11/VCFW1.jpg", w:2416, h:2272, title:"Running diagnostics and consulting the RK11-C prints..."},
                            {src:"/images/pdp11/VCFW2.jpg", w:4032, h:3024, title:"Pavl stops by with an RX02 and controller to help out with debug.  Replacement KM11 debug board visible in the upper diagnostic port of the RK11-C."},
                            {src:"/images/pdp11/VCFW4.jpg", w:1536, h:2048, title:"With Pete Richert, an old friend from Digidesign days!"},
                            {src:"/images/pdp11/dap-layout.png", w:842, h:604, title:"Corner of DAP layout from 1974 drawings"},
                            {src:"/images/pdp11/dap-corner.png", w:4032, h:3024, title:"Corner of one of my DAP boards.  Note missing R17."},
                            {src:"/images/pdp11/ubc-layout.png", w:1562, h:1116, title:"Corner of UBC layout from 1974 drawings"},
                            {src:"/images/pdp11/ubc-corner.jpeg", w:3905, h:2928, title:"Corner of one of my UBC boards.  Note missing W1, R161, and unpopulated E57."},
                            {src:"/images/pdp11/DAP-E42.jpeg", w:2015, h:2015, title:"Evidence of FCO M8100-A00002A around E42 on DAP board"},
                            {src:"/images/pdp11/dl11-user-hack.jpg", w:3024, h:4032, title:"DL11 with end-user hack"},
                            {src:"/images/pdp11/dl11-hack-front.png", w:3024, h:3024, title:"DL11 user hack front"},
                            {src:"/images/pdp11/dl11-hack-back.png", w:3024, h:3024, title:"DL11 user hack back"},
                            {src:"/images/pdp11/1134-serial.jpeg", w:4032, h:3024, title:"PDP-11/34: serial number tag"},
                            {src:"/images/pdp11/1134-chassis-sticker.jpeg", w:3024, h:3024, title:"PDP-11/34: BA11-K chassis sticker dating the system to 1976"},
                            {src:"/images/pdp11/1134-ohio-nuclear.jpg", w:4032, h:3024, title:"PDP-11/34: partial sticker for 'Ohio Nuclear' -- manufacturers of CT systems"},
                            {src:"/images/pdp11/1134-brackets-2.jpg", w:2438, h:1828, title:"PDP-11/34: BA11-K front panel mounting bracket"},
                            {src:"/images/pdp11/1134-brackets-3.jpeg", w:3024, h:4032, title:"PDP-11/34: BA11-K front panel mounting detail, with nylon spacers to make room for pre-filter"},
                            {src:"/images/pdp11/1134-brackets-4.jpeg", w:3024, h:3024, title:"PDP-11/34: Front panel mounted with replacement air pre-filter in place behind brackets and replacement power knob"},
                            {src:"/images/pdp11/H765-power-controller.jpeg", w:3024, h:3024, title:"PDP-11/34: H765 power controller module cleaned with new line cord"},
                            {src:"/images/pdp11/H765-transformer.jpeg", w:3024, h:3024, title:"PDP-11/34: H765 power supply main transformer, with modern X2 safety caps (orange) installed"},
                            {src:"/images/pdp11/H744-load-test.png", w:2256, h:1688, title:"PDP-11/34: Load testing an H744 DC regulator module; 'scope displays switching waveform"},
                            {src:"/images/pdp11/1134-memory.jpeg", w:4032, h:3024, title:"PDP-11/34: Monolithic Systems memory card"},
                            {src:"/images/pdp11/1134-M9301.jpeg", w:3024, h:3024, title:"A troublesome M9301 boot ROM card in a PDP-11/34, out on a card extender for troubleshooting.  This one was acting strangely at power-up; the problem is actually visible in this picture..."},
                            {src:"/images/pdp11/1134-frieda.jpeg", w:4032, h:3024, title:"Frieda approved PDP-11/34"},
                            {src:"/images/pdp11/unibone-kit.jpeg", w:4032, h:3024, title:"Unibone: unassembled kit"},
                            {src:"/images/pdp11/unibone-handles.jpeg", w:3024, h:3024, title:"Unibone: 3d printed handles"},
                            {src:"/images/pdp11/unibone-assembled.jpeg", w:3024, h:3024, title:"Unibone assembled"},
                            {src:"/images/pdp11/basic-mandel-output.jpeg", w:4032, h:3024, title:"BASIC-11 Mandelbrot program on a PDP-11/34, program output"},
                            {src:"/images/pdp11/basic-mandel-list.jpeg", w:4032, h:3024, title:"BASIC-11 Mandelbrot program on a PDP-11/34, program listing"},
                            {src:"/images/pdp11/VR14-screen-rot.JPG", w:3122, h:1757, title:"GT40 display (VR14) with screen rot"},
                            {src:"/images/pdp11/VR14-digesting.JPG", w:4032, h:3024, title:"Silicone digester repeatedly injected beneath the retaining ring, and softened silicone sraped away a layer at a time."},
                            {src:"/images/pdp11/VR14-apart.JPG", w:4032, h:3024, title:"After a week of work the retaining ring was freed and the layers were able to be separated and cleaned."},
                            {src:"/images/pdp11/VR14-plexi.JPG", w:4032, h:3024, title:"Conforming plexiglass in the oven to fill the gap between the display tube and the implosion shield where the PVA used to be."},
                            {src:"/images/pdp11/VR14-working.png", w:2420, h:1814, title:"Display re-assembled and working, driven by a test oscillator, and looking nice!"},
                            {src:"/images/pdp11/GT40-KM11.jpg", w:3024, h:4032, title:"GT40 system unit with KM11 replica board and microcode control board out on debug extender below.  The next microcode address is displayed in the bottom two rows of LEDs, with the LSB at the bottom right. Dark LEDs are logic 1, and lit are logic 0.  The next address displayed here is octal 316. From the microcode listings, we can see we are about to branch to micro-state CCS-1 (console continue switch), and can deduce that we are currently in micro-state H-2, about to branch out of the halt microcode loop to the continue switch handler."},
                            {src:"/images/pdp11/GT40-good-sign.jpeg", w:4032, h:3024, title:"First sign of end-to-end life on the GT40: terminal emulator boostrap running, and rendering received characters."},
                            {src:"/images/pdp11/GT40-square.jpeg", w:3024, h:3024, title:"GT40 display list processor running, rendering a square."},
                            {src:"/images/pdp11/gt40-line-feeds.jpg", w:540, h:720, title:"GT40 displaying multiple lines after CMPB (R2)+,R0 fix."},
                            {src:"/images/pdp11/gt40-first-lunar-run.jpg", w:540, h:720, title:"GT40 running the lunar lander game, but still with some display issues."},
                            {src:"/images/pdp11/gt40-diags.jpg", w:720, h:540, title:"Repaired GT40 running diagnostic MAINDEC-DDGTE."},
                            {src:"/images/pdp11/gt40-lunar-better.jpg", w:720, h:540, title:"Repaired GT40 running the lunar lander game."},
                            {src:"/images/pdp11/gt40-cheeseburger.jpg", w:720, h:540, title:"Repaired GT40: Scott lands on the moon and gets his cheesburger!"},
                    ],
            radios: [
                            {src:"/images/radios/travler-5028.jpeg", w:4032, h:3024, title:"A 1948 Trav-ler 5028 portable tube AM radio"},
                            {src:"/images/radios/travler-chassis.jpeg", w:4032, h:3024, title:"Trav-ler 5028 chassis"},
                            {src:"/images/radios/travler-beneath.jpeg", w:4032, h:3024, title:"Trav-ler 5028 chassis underside"},
                            {src:"/images/radios/travler-parts.jpeg", w:4032, h:3024, title:"Trav-ler radio disassembled"},
                            {src:"/images/radios/hickock.jpeg", w:3024, h:3024, title:"Testing tubes on the Hickock 533A"},
                            {src:"/images/radios/travler-orig-cap.jpeg", w:3024, h:3024, title:"Original multi-stage filter cap for the Trav-ler"},
                            {src:"/images/radios/travler-replacement-cap.jpeg", w:3024, h:3024, title:"Replacement multi-stage filter cap for the Trav-ler, made from one inch diameter model-rocketry body tube"},
                            {src:"/images/radios/travler-rebuild.jpeg", w:4032, h:3024, title:"Trav-ler point-to-point rebuild"},
                            {src:"/images/radios/travler-if.jpeg", w:3024, h:3024, title:"Opening one of the IF transformer cans from the Trav-ler"},
                            {src:"/images/radios/travler-if2.jpeg", w:3024, h:3024, title:"Interior detail of IF transformer.  Adjustable ferrite slugs screw inward and outward over two coils; integrated mica capacitors at the bottom have already been removed and their contact legs peeled back."},
                            {src:"/images/radios/travler-if-tweak.jpeg", w:3024, h:3024, title:"De-capped Trav-ler IF transformers re-installed, and temporary trimmer caps in place"},
                            {src:"/images/radios/fluke-ac-bridge.jpeg", w:3773, h:2830, title:"Fluke AC bridge, here being used to measure a potential replacement silver mica cap for the Trav-ler IF stage"},
                    ],
            puzzles: [
                            {src:"/images/puzzles/pyramid-together.jpeg", w:3024, h:3024, title:"Project Genius pyramid puzzle, assembled"},
                            {src:"/images/puzzles/pyramid-apart.jpeg", w:3024, h:3024, title:"Project Genius pyramid puzzle, disassembled"},
                    ],
            arcades: [
                            {src:"/images/arcades/tempests.jpeg", w:3024, h:4032, title:"Atari Tempest cabaret and upright, in for repairs"},
                            {src:"/images/arcades/tempest-cabaret-guts.jpeg", w:3024, h:4032, title:"Atari Tempest cabaret insides"},
                            {src:"/images/arcades/tempest-bench.png", w:1911, h:1067, title:"Atari Tempest running on the bench"},
                            {src:"/images/arcades/wg6100-deflection-parasitic.jpeg", w:1024, h:768, title:"A parasitic oscillation from a conterfeit deflection transistor in a WG6100 vector monitor.  Stimulus is a 1 KHz 8V p-p sine wave.  Parasitic initiates near cross-over."},
                            {src:"/images/arcades/wg6100-deflection-parasitic-zoomed.jpeg", w:1024, h:768, title:"Zoom in on parasitic oscillation in WG6100 deflection amplifier.  Parasitic is approx 4 MHz 200 mV."},
                    ],
            micros: [
                            {src:"/images/micros/vm4209-crt.jpeg", w:3024, h:3024, title:"VM4209: CRT"},
                            {src:"/images/micros/vm4209-chassis.jpeg", w:3024, h:3024, title:"VM4209: chassis with CRT removed"},
                            {src:"/images/micros/vm4209-bottom.jpeg", w:3024, h:3024, title:"VM4209: underside of main board"},
                            {src:"/images/micros/vm4209-vtrans.jpeg", w:3024, h:3024, title:"VM4209: vertical deflection heat sink, with Q106 replacement"},
                            {src:"/images/micros/vm4209-appleii.jpeg", w:3024, h:3024, title:"VM4209: repaired, with Apple II Plus"},
                            {src:"/images/micros/apple-ii-rifa.jpeg", w:3024, h:3024, title:"Blown RIFA capacitor from Apple II Plus power supply"},
                            {src:"/images/micros/apple-ii-pwr-before.jpeg", w:3024, h:4032, title:"Apple II Plus power supply before cap replacements"},
                            {src:"/images/micros/apple-ii-pwr-after.jpeg", w:3024, h:4032, title:"Apple II Plus power supply after cap replacements"},
                            {src:"/images/micros/apple-ii-lang-card.jpeg", w:4032, h:3024, title:"Apple II Plus language card repairs: yellow indicates two chips that were found swapped on the card; red indicates a failed 4116 RAM chip that was replaced."},
                            {src:"/images/micros/apple-ii-repaired.jpeg", w:3024, h:3024, title:"Apple II Plus: Successful DOS 3.3 boot after language card repairs"},
                    ],
    };
